In [2]:
import numpy as np

### Creating a 1D array

In [3]:
arr = np.array([1, 2, 3])
print(arr)
print("number of dimension: ",arr.ndim)

[1 2 3]
number of dimension:  1


### Creating a 2D array

In [4]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2d)
print("number of dimension: ",arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
number of dimension:  2


### Array Atrributes

In [5]:
# checking number of dimension
print(arr_2d.ndim)

# checking shape of the array
print(arr_2d.shape)

# checking total number of the elements
print(arr_2d.size)

# checking data type of elements
print(arr_2d.dtype)

2
(2, 3)
6
int32


### indexing

In [6]:
# Define a numpy array
arr = np.array([1, 2, 3, 4, 5])

# Access the first element
print(arr[0])

# Access the third element
print(arr[2])

# Access the last element
print(arr[-1])


1
3
5


In [7]:
# Define a 2D numpy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d)
# Access the first element of the first row
print(arr_2d[0, 0]) 

# Access the third element of the second row
print(arr_2d[1, 2])

# Access the second element of the last row
print(arr_2d[-1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6
8


### Slicing

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# slicing from the index 1 to index 5
print(arr[1:6])

# slicing frm the beginning to index 4
print(arr[:5])

# slicing from index 5to the end of the array
print(arr[5:])

# slicing evry other element in the array
print(arr[::2])


[1 2 3 4 5]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [9]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])


# slicing first 2 rows and 3 columns
print(arr_2d[:2, :3])

# slicing all rows and the last two columns
print(arr_2d[:, -2:])

print(arr_2d[1, -3])

[[1 2 3]
 [6 7 8]]
[[ 4  5]
 [ 9 10]
 [14 15]]
8


### Basic Operations

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
# print(arr1 + arr2)

# Subtraction
# print(arr1 - arr2)

# Multiplication
# print(arr1 * arr2)

# Division
print(arr2 / arr1)

[4.  2.5 2. ]


### Aggregation Functions

In [11]:
arr1 = np.array([1, 2, 3])

# print(arr1.sum())

# print(arr1.min())

# print(arr1.max())

# print(arr1.mean())

# print(np.average(arr1))

print(arr1.std())

0.816496580927726


### example

In [12]:
a = np.array([13, 15, 14, 14,13])
b = np.array([10, 20, 10, 20, 10])

print(a.mean())
print(b.mean())
print("---------")
print(a.std())
print(b.std())

13.8
14.0
---------
0.7483314773547882
4.898979485566356


### variance

In [33]:
a = np.array([1, 2, 3])

v = a.var()
print(v)

s = np.sqrt(v)

print(s)

sd = a.std()

print(sd)

0.6666666666666666
0.816496580927726
0.816496580927726


### Reshaping 

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr)
# print(arr.reshape(3, 2))

### Flattening

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### student grades

In [59]:
scores = np.array([
    [13, 14, 13, 17, 20],
    [20, 15, 19, 20, 15],
    [17, 20, 12, 18, 19],
])

flattened_scores = scores.flatten()
print(flattened_scores)

reshaped_scores = flattened_scores.reshape(3, 5)
print(reshaped_scores)

[13 14 13 17 20 20 15 19 20 15 17 20 12 18 19]
[[13 14 13 17 20]
 [20 15 19 20 15]
 [17 20 12 18 19]]


### project

In [90]:
grades = np.array([
    [20, 20, 20, 20, 20],
    [15, 17, 16, 16, 16],
    [18, 19, 19, 20, 19],
    [14, 13, 14, 15, 14],
    [17, 18, 18, 18, 18],
    [12, 12, 13, 13, 13],
    [15, 16, 15, 15, 14],
    [18, 18, 18, 19, 18],
    [16, 17, 16, 17, 16],
    [13, 13, 14, 14, 14]
])
class_average = np.mean(grades)
print(average)

student_averages = np.mean(grades, axis=1)
print("student averages: ",student_averages)

16.26
student averages:  [20.  16.  19.  14.  17.8 12.6 15.  18.2 16.4 13.6]


In [91]:
top_students = np.argsort(student_averages)[-3:][::-1]
print("top students: ",top_students + 1)

top students:  [1 3 8]


In [106]:
subject_averages = np.mean(grades, axis=0)
print("subject averages: ", subject_averages)

top_subject = np.argmax(subject_averages)
print("top subject: ", top_subject)

subjects = ["Math", "Physics", "Biology", "English", "History"]
print(f"top subject is: {subjects[top_subject]}")


subject averages:  [15.8 16.3 16.3 16.7 16.2]
top subject:  3
top subject is: English


In [108]:
variances = np.var(grades, axis=0)
print(variances)
stds = np.std(grades, axis=0)
print(stds)

[5.56 6.81 5.01 5.61 5.36]
[2.35796522 2.60959767 2.23830293 2.36854386 2.31516738]


In [129]:
top_grades = np.all(grades > 17, axis=1)
a = np.array([1,2,3])
counts = np.sum(a)
print(counts)

6
